### ISSUE TITLE
create object instantiator for CS and IRQ pins

### ISSUE THREAD

**Issue by ladyada** [adafruit/TinyLoRa#1]
instead of #defines, you should be able to set the pins when you create the TinyLora object
like this
https://github.com/adafruit/Adafruit_MAX31865/blob/master/Adafruit_MAX31865.cpp#L40
but of course for just the CS and IRQ pins. SPI should still be hardware SPI only

**Comment by brentru** [comment]
Merged into master/approved, closing...
