### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by wero1414** [adafruit/TinyLoRa#14]
Hi, i was reading the library repo and realize that this two links are broken 

- Documentation - https://learn.adafruit.com/the-things-network-for-feather/using-a-feather-32u4
- API - https://adafruit.github.io/TinyLoRa/html/index.html

**Comment by brentru** [comment]
Hi @wero1414: The first link should be live now (it was in the middle of being edited). I'm not exactly sure why Travis isn't deploying Doxygen (2nd link), I'll look into it.

**Comment by brentru** [comment]
Doxygen is now building to `gh-pages` branch (https://adafruit.github.io/TinyLoRa/html/index.html), both links work.

Closing....
