### ISSUE TITLE
Lose packets LoRa 32u4 ll

### ISSUE THREAD

**Issue by camilo-17** [adafruit/TinyLoRa#31]
Hello everyone, I am working with the Lora 32u4ll of BsFrance and a gateway kernel, it works, transmits to Yeap (a lora provider) but the RSSI is very low, around -117 and my lora 32u4ll is very close of the antenna of Gateway Someone knows what happens?

I would greatly appreciate your help.

**Comment by clavisound** [comment]
@camilo17 Have you solved this? I have the same problem. I think the problem is after the the pull #30.

**Comment by camilo-17** [comment]
Hello @clavisound see the documentation about your Gateway and look the Frequencies that it work 


Sorry if you don't understand my English its not good

**Comment by clavisound** [comment]
Thank you, but I don't changed my gateway settings and I have the same results from node to node :-(

**Comment by camilo-17** [comment]
Which frequency plan are you using ? And which Gateway?

**Comment by clavisound** [comment]
@camilo-17 Mystery solved. For some reason #include EU863 is ignored by TinyLoRa.h Inexplicable to me. I remember it worked! 10 days of my life gone for that :-/

You are ok with #define EU863 in your sketch? Or you modified TinyLoRa.h?
