### ISSUE TITLE
power off/standby api before putting arduino to sleep?

### ISSUE THREAD

**Issue by jhjulkun** [adafruit/TinyLoRa#39]
I looked but didn't see a "power off/sleep" api to use before putting an arduino in deep sleep?
After looking at code, it seems like the device is put to standby after every message, but was hoping there was something that puts RFM95 in minimal power usage. I looked at the RFM95 specs, but it wasn't clear at all.

**Comment by brentru** [comment]
The code puts the rfm9x into standby but lacks an explicit power off/sleep function. I'd be open to a pull request if you'd like to add it.

**Comment by jhjulkun** [comment]
Did some further testing, the drain I thought was from the radio seems to be something else, putting device in standby after each message is easier, as you don't need to begin() device next time waking from sleep.
