### ISSUE TITLE
allow multi/single channel selection via function not #define

### ISSUE THREAD

**Issue by ladyada** [adafruit/TinyLoRa#6]
maybe function is called setChannel() and you pass in an enumerated list of frequencies or MULTICHANNEL?

see this for an example on how to pass in an enumrated list of constants
https://github.com/adafruit/Adafruit_VEML6075/blob/master/Adafruit_VEML6075.h#L48
https://github.com/adafruit/Adafruit_VEML6075/blob/master/Adafruit_VEML6075.cpp#L132

**Comment by brentru** [comment]
should I also make spreading factor & bandwidth selection a separate function?

**Comment by ladyada** [comment]
yep!

**Comment by brentru** [comment]
Added DR and Channel selection to master, closing...
